/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

/*
题目：
给定两个只由小写字母组成的字符串s和t，
字符串t是由字符串s随机打乱排序后在任意位置添加一个字母产生的。
找到t中添加的那个字母。

分析：
将两个字符串合并为一个字符串，
再将合并后的字符串转换为一个字符数组，
用一个集合存储所有字母出现的次数，
此处可以参考136. Single Number这一题的方法，
如果该字母出现的次数为奇数，则说明该字母为所求。
 */

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    var arr = (s + t).split("");
    var count = {};
    for (let i=0; i<arr.length; i++) {
        if (count[arr[i]] === undefined) {
            count[arr[i]] = 1;
        } else {
            count[arr[i]]++;
        }
    }
    for (let c in count) {
        if (count[c] % 2 === 1) {
            return c;
        }
    }
};

/*
另一种方法：
先将两个字符串都转为字符数组操作，
然后遍历字符数组，
如果t字符数组中出现s字符数组中的字母，
则将该字母从t字符数组中移除，
最后返回剩下的那个字母即可。
 */

var findTheDifference = function(s, t) {
    var sArr = s.split("");
    var tArr = t.split("");
    for (let i=0; i<sArr.length; i++) {
        for (let j=0; j<tArr.length; j++) {
            if (sArr[i] === tArr[j]) {
                tArr.splice(j,1);
                break;
            }
        }
    }
    return tArr[0];
};
